services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    shm_size: "2gb"
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - XQSIM_TRACE_TIMEOUT_SECONDS=7200  # 2 hours
